

Sys.setenv(LANG="en_US.UTF-8")

if (!requireNamespace("backports", quietly = TRUE))
  install.packages('backports')
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
if (!requireNamespace("usethis", quietly = TRUE))
  install.packages("usethis")
if (!requireNamespace("devtools", quietly = TRUE))
  # install.packages("devtools")
  install.packages("devtools", type = "win.binary")
if (!requireNamespace("dplyr", quietly = TRUE))
  install.packages("dplyr")
if (!requireNamespace("DT", quietly = TRUE))
  install.packages('DT')
if (!requireNamespace("feather", quietly = TRUE))
  install.packages('feather')
if (!requireNamespace("ggthemes", quietly = TRUE))
  install.packages('ggthemes')
if (!requireNamespace("gplots", quietly = TRUE))
  install.packages("gplots")
if (!requireNamespace("grImport2", quietly = TRUE))
  install.packages('grImport2')
if (!requireNamespace("gWidgetsRGtk2", quietly = TRUE))
  install.packages("gWidgetsRGtk2")
if (!requireNamespace("HH", quietly = TRUE))
  install.packages('HH')
if (!requireNamespace("igraph", quietly = TRUE))
  install.packages("igraph")
if (!requireNamespace("markdown", quietly = TRUE))
  install.packages('markdown')
if (!requireNamespace("Metrics", quietly = TRUE))
  install.packages('Metrics')
if (!requireNamespace("networkD3", quietly = TRUE))
  install.packages('networkD3')
if (!requireNamespace("plotly", quietly = TRUE))
  install.packages('plotly')
if (!requireNamespace("plotmo", quietly = TRUE))
  install.packages('plotmo')
if (!requireNamespace("processx", quietly = TRUE))
  install.packages("processx")
if (!requireNamespace("RColorBrewer", quietly = TRUE))
  install.packages('RColorBrewer')
if (!requireNamespace("rmarkdown", quietly = TRUE))
  install.packages('rmarkdown')
if (!requireNamespace("shiny", quietly = TRUE))
  install.packages('shiny')
if (!requireNamespace("shinycssloaders", quietly = TRUE))
  install.packages('shinycssloaders')
if (!requireNamespace("shinydashboard", quietly = TRUE))
  install.packages('shinydashboard')
if (!requireNamespace("tidymodels", quietly = TRUE))
  install.packages('tidymodels')
if (!requireNamespace("tidyverse", quietly = TRUE))
  install.packages('tidyverse')
if (!requireNamespace("yaml", quietly = TRUE))
  install.packages('yaml')

BiocManager::install('bgsmtr')
BiocManager::install('BiocVersion')
BiocManager::install("cgdsr")
BiocManager::install('clusterProfiler')
BiocManager::install("ComplexHeatmap")
BiocManager::install('DESeq')
BiocManager::install('edgeR')
BiocManager::install('gage')
BiocManager::install('gageData')
BiocManager::install('limma')
BiocManager::install('L0Learn')
BiocManager::install('org.Hs.eg.db')
BiocManager::install('pathview')
BiocManager::install('pheatmap')
BiocManager::install("rtracklayer")
BiocManager::install("WGCNA")

# devtools::install_github("tidyverse/ggplot2")
# devtools::install_github('GuangchuangYu/clusterProfiler')

